---
name: CI

on: [push]

jobs:
  ut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        run: docker run -v $PWD:/yaml sdesbure/yamllint yamllint -s .
      - name: markdownlint
        run: docker run -i -v $PWD:/work tmknom/markdownlint -c .markdownlint.json .
