---
name: CI

on: [push]

env:
  # このパイプラインで実行しない処理をスキップするための環境識別用変数
  ORE_NO_GAMING_WINDOWS_CICD_PIPELINE: true

jobs:
  ut:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install molecule
        run: pip3 install -r requirements.txt
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: yamllint
        run: yamllint -s .
      - name: ansible-lint
        run: ansible-lint
      - name: markdownlint
        run: markdownlint -c .markdownlint.json .
